// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLJUGly2LYofZrHbRQ-rqoyiLl8EivDno',
    appId: '1:605182692141:web:9204b7cb57be18cc7be1a4',
    messagingSenderId: '605182692141',
    projectId: 'pokedex-2a6df',
    authDomain: 'pokedex-2a6df.firebaseapp.com',
    storageBucket: 'pokedex-2a6df.firebasestorage.app',
    measurementId: 'G-GNJEVDLQQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6u4clR2A8ixdIFFG2fSLgWTdCws0Huqc',
    appId: '1:605182692141:android:55a2b06c1f6793797be1a4',
    messagingSenderId: '605182692141',
    projectId: 'pokedex-2a6df',
    storageBucket: 'pokedex-2a6df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB0-XsYHA4QdRvAvz9yt_Dqyn9J2_-xbA',
    appId: '1:605182692141:ios:55dc8b56e811bd017be1a4',
    messagingSenderId: '605182692141',
    projectId: 'pokedex-2a6df',
    storageBucket: 'pokedex-2a6df.firebasestorage.app',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB0-XsYHA4QdRvAvz9yt_Dqyn9J2_-xbA',
    appId: '1:605182692141:ios:55dc8b56e811bd017be1a4',
    messagingSenderId: '605182692141',
    projectId: 'pokedex-2a6df',
    storageBucket: 'pokedex-2a6df.firebasestorage.app',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLJUGly2LYofZrHbRQ-rqoyiLl8EivDno',
    appId: '1:605182692141:web:9bc7a4bf34a681e87be1a4',
    messagingSenderId: '605182692141',
    projectId: 'pokedex-2a6df',
    authDomain: 'pokedex-2a6df.firebaseapp.com',
    storageBucket: 'pokedex-2a6df.firebasestorage.app',
    measurementId: 'G-KSR298TWHL',
  );

}